name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - run: pip install mypy
      - run: mypy src tests --install-types --non-interactive --ignore-missing-imports --implicit-optional --disallow-untyped-defs


